run-migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -212,27 +212,25 @@ jobs:
             echo -e "[migrations]\n" > migrations.txt
             npm i
             npm run build
-            npm run migrations > migrations.txt
+            npm run migrations >> migrations.txt
             cat migrations.txt
       - run:
           name: Send migration results to memstash
           command: |
             cd backend
             cat migrations.txt
-            # migration=$( tail -n 1 migrations.txt)
-            # echo $migration
-            # if echo "$migration" | grep -q "has been executed successfully"; then 
-            #   curl -H "Content-Type: text/plain" -H "token:154b0161-90a0-4670-a255-6a72c99dd5ad" --request PUT --data "1" https://api.memstash.io/values/migration
-            #   echo "Send migration results to memstash: successful"
-            # else
-            #   curl -H "Content-Type: text/plain" -H "token:154b0161-90a0-4670-a255-6a72c99dd5ad" --request PUT --data "0" https://api.memstash.io/values/migration
-            #   echo "Send migration results to memstash: failed"
-            #   exit 1
-            # fi
-
+            migration=$( tail -n 1 migrations.txt)
+            echo $migration
+            if echo "$migration" | grep -q "has been executed successfully"; then 
+              curl -H "Content-Type: text/plain" -H "token:154b0161-90a0-4670-a255-6a72c99dd5ad" --request PUT --data "1" https://api.memstash.io/values/migration
+              echo "Send migration results to memstash: successful"
+            else
+              curl -H "Content-Type: text/plain" -H "token:154b0161-90a0-4670-a255-6a72c99dd5ad" --request PUT --data "0" https://api.memstash.io/values/migration
+              echo "Send migration results to memstash: failed"
+              exit 1
+            fi
             URLS=$(curl -H "token: 154b0161-90a0-4670-a255-6a72c99dd5ad" --request GET https://api.memstash.io/values/migration)
-            echo "$URLS"
-
+            echo "${URLS}"
       - save_cache:
           key: node_modules
           paths:
@@ -254,10 +252,8 @@ jobs:
       - run:
           name: Get backend url
           command: |
-            export BACKEND_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:project,Values=udapeople" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
+            BACKEND_IP=$(curl -H "token: 154b0161-90a0-4670-a255-6a72c99dd5ad" --request GET https://api.memstash.io/values/ipaddress)
+            echo "${BACKEND_IP}"
             export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
             echo "API_URL=$API_URL" > frontend/.env
