URLS

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -223,14 +223,17 @@ jobs:
             cat migrations.txt
             migration=$( tail -n 1 migrations.txt)
             echo $migration
-            if echo "$migration" | grep -q "has been executed successfully"; then 
-              curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "succeeded" https://api.memstash.io/values/1
-              echo "Send migration results to memstash: successful"
-            else
-              curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "failed" https://api.memstash.io/values/migration_failed_${CIRCLE_WORKFLOW_ID}
-              echo "Send migration results to memstash: failed"
-              exit 1
-            fi
+            # if echo "$migration" | grep -q "has been executed successfully"; then 
+            #   curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "succeeded" https://api.memstash.io/values/1
+            #   echo "Send migration results to memstash: successful"
+            # else
+            #   curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "failed" https://api.memstash.io/values/migration_failed_${CIRCLE_WORKFLOW_ID}
+            #   echo "Send migration results to memstash: failed"
+            #   exit 1
+            # fi
+            curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f" --request PUT --data "true" https://api.memstash.io/values/$migration
+            URLS=$(curl -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f" --request GET https://api.memstash.io/values/1)
+            echo "$URLS"
             #exit 1
       - save_cache:
           key: node_modules
