echo $migration

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -223,15 +223,15 @@ jobs:
             cat migrations.txt
             migration=$( tail -n 1 migrations.txt)
             echo $migration
-            if grep "has been executed successfully" $migration
-            then 
-              curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "succeeded" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
-              echo "Send migration results to memstash: successful"
-            else
-              curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "failed" https://api.memstash.io/values/migration_failed_${CIRCLE_WORKFLOW_ID}
-              echo "Send migration results to memstash: failed"
-              exit 1
-            fi
+            # if grep "has been executed successfully" $migration
+            # then 
+            #   curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "succeeded" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+            #   echo "Send migration results to memstash: successful"
+            # else
+            #   curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "failed" https://api.memstash.io/values/migration_failed_${CIRCLE_WORKFLOW_ID}
+            #   echo "Send migration results to memstash: failed"
+            #   exit 1
+            # fi
             exit 1#cancel intentional
       - save_cache:
           key: node_modules
@@ -288,7 +288,8 @@ jobs:
           name: Deploy backend
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
+      - destroy-environment
+      - revert-migration
 
   smoke-test:
     docker:
