# cat migrations.txt

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -215,23 +215,22 @@ jobs:
             npm i
             npm run build
             npm run migrations > migrations.txt
-            cat migrations.txt
+            # cat migrations.txt
       - run:
           name: Send migration results to memstash
           command: |
             cd backend
-            cat migrations.txt
+            # cat migrations.txt
             migration=$( tail -n 1 migrations.txt)
             echo $migration
-            # if echo "$migration" | grep -q "has been executed successfully"; then 
-            #   curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "succeeded" https://api.memstash.io/values/1
-            #   echo "Send migration results to memstash: successful"
-            # else
-            #   curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "failed" https://api.memstash.io/values/migration_failed_${CIRCLE_WORKFLOW_ID}
-            #   echo "Send migration results to memstash: failed"
-            #   exit 1
-            # fi
-            curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f" --request PUT --data "true" https://api.memstash.io/values/$migration
+            if echo "$migration" | grep -q "has been executed successfully"; then 
+              curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "succeeded" https://api.memstash.io/values/1
+              echo "Send migration results to memstash: successful"
+            else
+              curl -H "Content-Type: text/plain" -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f --request PUT --data "failed" https://api.memstash.io/values/migration_failed_${CIRCLE_WORKFLOW_ID}
+              echo "Send migration results to memstash: failed"
+              exit 1
+            fi
             URLS=$(curl -H "token: 1ee08d36-38af-43ec-bcab-8fdf47b7d94f" --request GET https://api.memstash.io/values/1)
             echo "$URLS"
       - run:
