run-migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -197,7 +197,7 @@ jobs:
 
   run-migrations:
     docker:
-      - image: circleci/node
+      - image: circleci/node:latest
     steps:
       - checkout
       - restore_cache:
@@ -209,30 +209,31 @@ jobs:
           name: Run migrations
           command: |
             cd backend
-            echo -e "[migrations]\n" > migrations.txt
-            npm i
-            npm run build
+            touch migrations.txt
+            npm install
             npm run migrations >> migrations.txt
             cat migrations.txt
             npm fund
             npm audit fix
+            npm run migrations >> migrations.txt
+            cat migrations.txt
       - run:
           name: Send migration results to memstash
           command: |
             cd backend
             cat migrations.txt
-            migration=$( tail -n 1 migrations.txt)
-            echo $migration
-            if echo "$migration" | grep -q "has been executed successfully"; then 
-              curl -H "Content-Type: text/plain" -H "token:154b0161-90a0-4670-a255-6a72c99dd5ad" --request PUT --data "1" https://api.memstash.io/values/migration
-              echo "Send migration results to memstash: successful"
-            else
-              curl -H "Content-Type: text/plain" -H "token:154b0161-90a0-4670-a255-6a72c99dd5ad" --request PUT --data "0" https://api.memstash.io/values/migration
-              echo "Send migration results to memstash: failed"
-              exit 1
-            fi
-            URLS=$(curl -H "token: 154b0161-90a0-4670-a255-6a72c99dd5ad" --request GET https://api.memstash.io/values/migration)
-            echo "${URLS}"
+            # migration=$( tail -n 1 migrations.txt)
+            # echo $migration
+            # if echo "$migration" | grep -q "has been executed successfully"; then 
+            #   curl -H "Content-Type: text/plain" -H "token:154b0161-90a0-4670-a255-6a72c99dd5ad" --request PUT --data "1" https://api.memstash.io/values/migration
+            #   echo "Send migration results to memstash: successful"
+            # else
+            #   curl -H "Content-Type: text/plain" -H "token:154b0161-90a0-4670-a255-6a72c99dd5ad" --request PUT --data "0" https://api.memstash.io/values/migration
+            #   echo "Send migration results to memstash: failed"
+            #   exit 1
+            # fi
+            # URLS=$(curl -H "token: 154b0161-90a0-4670-a255-6a72c99dd5ad" --request GET https://api.memstash.io/values/migration)
+            # echo "${URLS}"
       - save_cache:
           key: node_modules
           paths:
@@ -351,27 +352,27 @@ cleanup:
 workflows:
   default:
     jobs:
-      - build-frontend
-      - build-backend
-      - test-frontend:
-          requires: [build-frontend]
-      - test-backend:
-          requires: [build-backend]
-      - scan-backend:
-          requires: [build-backend]
-      - scan-frontend:
-          requires: [build-frontend]
-      - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-          #requires: [build-frontend, build-backend]
-          filters:
-            branches:
-              only: [main]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
+      # - build-frontend
+      # - build-backend
+      # - test-frontend:
+      #     requires: [build-frontend]
+      # - test-backend:
+      #     requires: [build-backend]
+      # - scan-backend:
+      #     requires: [build-backend]
+      # - scan-frontend:
+      #     requires: [build-frontend]
+      # - deploy-infrastructure:
+      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+      #     #requires: [build-frontend, build-backend]
+      #     filters:
+      #       branches:
+      #         only: [main]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
+      - run-migrations
           #requires: [deploy-infrastructure]
-          requires: [configure-infrastructure]
+          #requires: [configure-infrastructure]
       # - deploy-frontend:
       #     requires: [run-migrations]
       # - deploy-backend:
